parserOptions:
  ecmaVersion: 6

extends: 
- eslint:recommended
- google

rules: 
  no-console: 0
  max-len: 
  - 2
  - 120

env:
  browser: true
  jquery: true

globals:
  g: true
  icons: true
  tinysort: true
  canvasToFavicon: true
  saveAs: true
  Fuse: true
